# Generated by Django 5.2 on 2025-04-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailentry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emailentry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
